<font size="7"><span style="color: #33D6CC;">OBTENCIÃ“N DE DATOS</span></font>

In [1]:
import pandas as pd 
import numpy as np

**Datos derivados de Jeff Sackmann's Tennis databases**

**Licencia original: CC BY-NC-SA 4.0**

**Fuente: https://github.com/JeffSackmann/tennis_atp**

In [2]:
lista_csv=[]
    # Recorrer csv's
for i in range(1968,2025): 
    ruta = f'atp_matches_{i}.csv'
    lista_csv.append(ruta)

    # Crear una lista vacÃ­a para almacenar los DataFrames de cada archivo CSV
lista_df = []

    # Leer cada archivo CSV y aÃ±adirlo a la lista
for archivo in lista_csv:
     df = pd.read_csv(archivo)
     lista_df.append(df)

    # Concatenar todos los DataFrames en uno solo
df = pd.concat(lista_df, ignore_index=True)
df

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,1968-2029,Dublin,Grass,32.0,A,19680708,270,112411,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1968-2029,Dublin,Grass,32.0,A,19680708,271,126914,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1968-2029,Dublin,Grass,32.0,A,19680708,272,209523,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1968-2029,Dublin,Grass,32.0,A,19680708,273,100084,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1968-2029,Dublin,Grass,32.0,A,19680708,274,100132,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193332,2024-M-DC-2024-WG2-PO-URU-MDA-01,Davis Cup WG2 PO: URU vs MDA,Clay,4.0,D,20240203,5,212051,NaN,NaN,...,30.0,17.0,7.0,6.0,8.0,14.0,1109.0,8.0,740.0,34.0
193333,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4.0,D,20240202,1,122533,NaN,NaN,...,41.0,25.0,6.0,9.0,1.0,4.0,554.0,67.0,748.0,32.0
193334,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4.0,D,20240202,2,144748,NaN,NaN,...,51.0,25.0,7.0,11.0,5.0,12.0,416.0,109.0,NaN,NaN
193335,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4.0,D,20240202,4,122533,NaN,NaN,...,51.0,32.0,17.0,14.0,5.0,9.0,554.0,67.0,416.0,109.0
193336,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4.0,D,20240202,5,202475,NaN,NaN,...,53.0,25.0,8.0,8.0,9.0,14.0,748.0,32.0,NaN,NaN

In [3]:
df.isnull().mean()*100

tourney_id             0.000000
tourney_name           0.000000
surface                1.546522
draw_size              0.431888
tourney_level          0.000000
tourney_date           0.000000
match_num              0.000000
winner_id              0.000000
winner_seed           62.995185
winner_entry          91.236546
winner_name            0.000000
winner_hand            0.005172
winner_ht              8.845177
winner_ioc             0.004138
winner_age             0.678091
loser_id               0.000000
loser_seed            81.133461
loser_entry           85.141489
loser_name             0.000000
loser_hand             0.025344
loser_ht              15.468327
loser_ioc              0.037241
loser_age              2.408747
score                  0.004655
best_of                0.000000
round                  0.000000
minutes               51.544712
w_ace                 50.116636
w_df                  50.117153
w_svpt                50.117153
w_1stIn               50.117153
w_1stWon              50.117153
w_2ndWon              50.117153
w_SvGms               50.116636
w_bpSaved             50.117153
w_bpFaced             50.117153
l_ace                 50.117153
l_df                  50.116636
l_svpt                50.117153
l_1stIn               50.117153
l_1stWon              50.117153
l_2ndWon              50.117153
l_SvGms               50.116636
l_bpSaved             50.117153
l_bpFaced             50.117153
winner_rank           18.500339
winner_rank_points    42.925565
loser_rank            22.838360
loser_rank_points     43.775894
dtype: float64

In [5]:
    #guardamos el df bruto en un csv
df.to_csv('tenis_bruto.csv',index=False)