<font size="7"><span style="color: #33D6CC;">LIMPIEZA DE LOS DATOS</span></font>

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt 
import re
from sklearn.impute import SimpleImputer

In [4]:
df = pd.read_csv('tenis_bruto.csv')
df

C:\Users\albam\AppData\Local\Temp\ipykernel_25728\584941035.py:1: DtypeWarning: Columns (8,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('tenis_bruto.csv')

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,1968-2029,Dublin,Grass,32.0,A,19680708,270,112411,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1968-2029,Dublin,Grass,32.0,A,19680708,271,126914,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1968-2029,Dublin,Grass,32.0,A,19680708,272,209523,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1968-2029,Dublin,Grass,32.0,A,19680708,273,100084,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1968-2029,Dublin,Grass,32.0,A,19680708,274,100132,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193332,2024-M-DC-2024-WG2-PO-URU-MDA-01,Davis Cup WG2 PO: URU vs MDA,Clay,4.0,D,20240203,5,212051,NaN,NaN,...,30.0,17.0,7.0,6.0,8.0,14.0,1109.0,8.0,740.0,34.0
193333,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4.0,D,20240202,1,122533,NaN,NaN,...,41.0,25.0,6.0,9.0,1.0,4.0,554.0,67.0,748.0,32.0
193334,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4.0,D,20240202,2,144748,NaN,NaN,...,51.0,25.0,7.0,11.0,5.0,12.0,416.0,109.0,NaN,NaN
193335,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4.0,D,20240202,4,122533,NaN,NaN,...,51.0,32.0,17.0,14.0,5.0,9.0,554.0,67.0,416.0,109.0
193336,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4.0,D,20240202,5,202475,NaN,NaN,...,53.0,25.0,8.0,8.0,9.0,14.0,748.0,32.0,NaN,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193337 entries, 0 to 193336
Data columns (total 49 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   tourney_id          193337 non-null  object
 1   tourney_name        193337 non-null  object
 2   surface             190347 non-null  object
 3   draw_size           192502 non-null  float64
 4   tourney_level       193337 non-null  object
 5   tourney_date        193337 non-null  int64
 6   match_num           193337 non-null  int64
 7   winner_id           193337 non-null  int64
 8   winner_seed         71544 non-null   object
 9   winner_entry        16943 non-null   object
 10  winner_name         193337 non-null  object
 11  winner_hand         193327 non-null  object
 12  winner_ht           176236 non-null  float64
 13  winner_ioc          193329 non-null  object
 14  winner_age          192026 non-null  float64
 15  loser_id            193337 non-null  int64
 16  loser_seed          36476 non-null   object
 17  loser_entry         28727 non-null   object
 18  loser_name          193337 non-null  object
 19  loser_hand          193288 non-null  object
 20  loser_ht            163431 non-null  float64
 21  loser_ioc           193265 non-null  object
 22  loser_age           188680 non-null  float64
 23  score               193328 non-null  object
 24  best_of             193337 non-null  int64
 25  round               193337 non-null  object
 26  minutes             93682 non-null   float64
 27  w_ace               96443 non-null   float64
 28  w_df                96442 non-null   float64
 29  w_svpt              96442 non-null   float64
 30  w_1stIn             96442 non-null   float64
 31  w_1stWon            96442 non-null   float64
 32  w_2ndWon            96442 non-null   float64
 33  w_SvGms             96443 non-null   float64
 34  w_bpSaved           96442 non-null   float64
 35  w_bpFaced           96442 non-null   float64
 36  l_ace               96442 non-null   float64
 37  l_df                96443 non-null   float64
 38  l_svpt              96442 non-null   float64
 39  l_1stIn             96442 non-null   float64
 40  l_1stWon            96442 non-null   float64
 41  l_2ndWon            96442 non-null   float64
 42  l_SvGms             96443 non-null   float64
 43  l_bpSaved           96442 non-null   float64
 44  l_bpFaced           96442 non-null   float64
 45  winner_rank         157569 non-null  float64
 46  winner_rank_points  110346 non-null  float64
 47  loser_rank          149182 non-null  float64
 48  loser_rank_points   108702 non-null  float64
dtypes: float64(28), int64(5), object(16)
memory usage: 72.3+ MB

# GENÉRICA

In [349]:
df.columns

Index(['tourney_id', 'tourney_name', 'surface', 'draw_size', 'tourney_level',
       'tourney_date', 'match_num', 'winner_id', 'winner_seed', 'winner_entry',
       'winner_name', 'winner_hand', 'winner_ht', 'winner_ioc', 'winner_age',
       'loser_id', 'loser_seed', 'loser_entry', 'loser_name', 'loser_hand',
       'loser_ht', 'loser_ioc', 'loser_age', 'score', 'best_of', 'round',
       'minutes', 'w_ace', 'w_df', 'w_svpt', 'w_1stIn', 'w_1stWon', 'w_2ndWon',
       'w_SvGms', 'w_bpSaved', 'w_bpFaced', 'l_ace', 'l_df', 'l_svpt',
       'l_1stIn', 'l_1stWon', 'l_2ndWon', 'l_SvGms', 'l_bpSaved', 'l_bpFaced',
       'winner_rank', 'winner_rank_points', 'loser_rank', 'loser_rank_points'],
      dtype='object')

In [350]:
df.isnull().mean()*100

tourney_id             0.000000
tourney_name           0.000000
surface                1.546522
draw_size              0.431888
tourney_level          0.000000
tourney_date           0.000000
match_num              0.000000
winner_id              0.000000
winner_seed           62.995185
winner_entry          91.236546
winner_name            0.000000
winner_hand            0.005172
winner_ht              8.845177
winner_ioc             0.004138
winner_age             0.678091
loser_id               0.000000
loser_seed            81.133461
loser_entry           85.141489
loser_name             0.000000
loser_hand             0.025344
loser_ht              15.468327
loser_ioc              0.037241
loser_age              2.408747
score                  0.004655
best_of                0.000000
round                  0.000000
minutes               51.544712
w_ace                 50.116636
w_df                  50.117153
w_svpt                50.117153
w_1stIn               50.117153
w_1stWon              50.117153
w_2ndWon              50.117153
w_SvGms               50.116636
w_bpSaved             50.117153
w_bpFaced             50.117153
l_ace                 50.117153
l_df                  50.116636
l_svpt                50.117153
l_1stIn               50.117153
l_1stWon              50.117153
l_2ndWon              50.117153
l_SvGms               50.116636
l_bpSaved             50.117153
l_bpFaced             50.117153
winner_rank           18.500339
winner_rank_points    42.925565
loser_rank            22.838360
loser_rank_points     43.775894
dtype: float64

In [351]:
    # Eliminación de columnas sin valor
columnas=['tourney_id','match_num','winner_seed','winner_entry','loser_seed','loser_entry']
df.drop(columns=columnas,inplace= True)
df.head(5)

,tourney_name,surface,draw_size,tourney_level,tourney_date,winner_id,winner_name,winner_hand,winner_ht,winner_ioc,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,Dublin,Grass,32.0,A,19680708,112411,Doug Smith,U,NaN,AUS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Dublin,Grass,32.0,A,19680708,126914,Louis Pretorius,R,NaN,RSA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Dublin,Grass,32.0,A,19680708,209523,Cecil Pedlow,U,NaN,IRL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Dublin,Grass,32.0,A,19680708,100084,Tom Okker,R,178.0,NED,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Dublin,Grass,32.0,A,19680708,100132,Armistead Neely,R,NaN,USA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [352]:
df.isnull().mean()*100

tourney_name           0.000000
surface                1.546522
draw_size              0.431888
tourney_level          0.000000
tourney_date           0.000000
winner_id              0.000000
winner_name            0.000000
winner_hand            0.005172
winner_ht              8.845177
winner_ioc             0.004138
winner_age             0.678091
loser_id               0.000000
loser_name             0.000000
loser_hand             0.025344
loser_ht              15.468327
loser_ioc              0.037241
loser_age              2.408747
score                  0.004655
best_of                0.000000
round                  0.000000
minutes               51.544712
w_ace                 50.116636
w_df                  50.117153
w_svpt                50.117153
w_1stIn               50.117153
w_1stWon              50.117153
w_2ndWon              50.117153
w_SvGms               50.116636
w_bpSaved             50.117153
w_bpFaced             50.117153
l_ace                 50.117153
l_df                  50.116636
l_svpt                50.117153
l_1stIn               50.117153
l_1stWon              50.117153
l_2ndWon              50.117153
l_SvGms               50.116636
l_bpSaved             50.117153
l_bpFaced             50.117153
winner_rank           18.500339
winner_rank_points    42.925565
loser_rank            22.838360
loser_rank_points     43.775894
dtype: float64

In [353]:
df.shape

(193337, 43)

In [354]:
    #quitar filas con minutes nulos
df = df.dropna(subset=['minutes'])
df.shape

(93682, 43)

In [355]:
    # NEXTGEN mecanismo del torneo diferente 
df = df[~df['tourney_name'].str.startswith('NextGen', na=False)]
df.shape

(93591, 43)

In [356]:
   # Eliminar los partidos walkover y retirados
df = df[df['score']!='W/O']
df = df[df['score']!=' W/O']
df = df[df['score']!=' RET']
df.shape

(93532, 43)

In [357]:
    # eliminar partidos de retirados,walkover o descalificados en score
df = df[~df['score'].str.contains('RET', na=False)]
df = df[~df['score'].str.contains('DEF', na=False)]
df = df[~df['score'].str.contains('Def.', na=False)]
df[df['score'].str.contains(' W/O', na=False)]['score']
df.shape

(91006, 43)

In [358]:
    #eliminar partidos con menos sets de los que hay que ganar según best_of
#variable sets por partido
sets=[]
for i in df.score:
     sets.append(len(i.split()))
   
df['sets']=sets
#eliminacion de los que se han jugado 2 y es al mejor de 5
df = df[~((df['sets']==2) & (df['best_of']==5))]
df.shape

(91005, 44)

In [363]:
    # eliminar outliers en minutos>350
df = df.query('minutes<350')
df.shape

(89212, 44)

In [364]:
    # eliminar los partidos de menos de 25 minutos excepto el de shangai que si es real
fila = df[(df['minutes']==25.0) & (df['tourney_name']=='Shanghai')]
df = df[df['minutes']>25.0]
df = pd.concat([df, fila], ignore_index=True)
df.shape

(89206, 44)

In [359]:
 # cambiar las filas con Carpet a partir de 2009 por Hard
df['tourney_date'] = df['tourney_date'].astype(str)
df.loc[(df['surface'] == 'Carpet') & (df['tourney_date'].str.startswith('2009')), 'surface'] = 'Hard'
df['tourney_date'] = df['tourney_date'].astype(int)

In [361]:
df.isnull().sum()

tourney_name             0
surface                  0
draw_size                0
tourney_level            0
tourney_date             0
winner_id                0
winner_name              0
winner_hand              3
winner_ht              537
winner_ioc               0
winner_age               1
loser_id                 0
loser_name               0
loser_hand              24
loser_ht              1459
loser_ioc                0
loser_age               19
score                    0
best_of                  0
round                    0
minutes                  0
w_ace                   19
w_df                    20
w_svpt                  20
w_1stIn                 20
w_1stWon                20
w_2ndWon                20
w_SvGms                 20
w_bpSaved               20
w_bpFaced               20
l_ace                   20
l_df                    19
l_svpt                  20
l_1stIn                 20
l_1stWon                20
l_2ndWon                20
l_SvGms                 20
l_bpSaved               20
l_bpFaced               20
winner_rank            272
winner_rank_points    1205
loser_rank             611
loser_rank_points     1536
sets                     0
dtype: int64

In [362]:
    # eliminamos los nulos de esas columnas por no poder asignarles valor (visto en numéricas)
df = df.dropna(subset=['winner_rank','winner_rank_points','loser_rank','loser_rank_points'])
df.shape

(89219, 44)

In [365]:
df.isnull().sum()

tourney_name             0
surface                  0
draw_size                0
tourney_level            0
tourney_date             0
winner_id                0
winner_name              0
winner_hand              0
winner_ht              463
winner_ioc               0
winner_age               0
loser_id                 0
loser_name               0
loser_hand               5
loser_ht              1231
loser_ioc                0
loser_age                7
score                    0
best_of                  0
round                    0
minutes                  0
w_ace                   16
w_df                    16
w_svpt                  16
w_1stIn                 16
w_1stWon                16
w_2ndWon                16
w_SvGms                 16
w_bpSaved               16
w_bpFaced               16
l_ace                   16
l_df                    16
l_svpt                  16
l_1stIn                 16
l_1stWon                16
l_2ndWon                16
l_SvGms                 16
l_bpSaved               16
l_bpFaced               16
winner_rank              0
winner_rank_points       0
loser_rank               0
loser_rank_points        0
sets                     0
dtype: int64

In [366]:
df.columns

Index(['tourney_name', 'surface', 'draw_size', 'tourney_level', 'tourney_date',
       'winner_id', 'winner_name', 'winner_hand', 'winner_ht', 'winner_ioc',
       'winner_age', 'loser_id', 'loser_name', 'loser_hand', 'loser_ht',
       'loser_ioc', 'loser_age', 'score', 'best_of', 'round', 'minutes',
       'w_ace', 'w_df', 'w_svpt', 'w_1stIn', 'w_1stWon', 'w_2ndWon', 'w_SvGms',
       'w_bpSaved', 'w_bpFaced', 'l_ace', 'l_df', 'l_svpt', 'l_1stIn',
       'l_1stWon', 'l_2ndWon', 'l_SvGms', 'l_bpSaved', 'l_bpFaced',
       'winner_rank', 'winner_rank_points', 'loser_rank', 'loser_rank_points',
       'sets'],
      dtype='object')

# NUMÉRICAS

In [367]:
    # DF de variables numéricas
df_num = df._get_numeric_data()
df_num

,draw_size,tourney_date,winner_id,winner_ht,winner_age,loser_id,loser_ht,loser_age,best_of,minutes,...,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,sets
0,32.0,19910107,101142,180.0,25.6,101746,175.0,20.6,3,63.0,...,17.0,7.0,8.0,2.0,6.0,9.0,1487.0,78.0,459.0,2
1,32.0,19910107,101613,180.0,21.5,100587,188.0,31.8,3,72.0,...,22.0,6.0,8.0,7.0,11.0,94.0,371.0,220.0,114.0,2
2,32.0,19910107,101179,185.0,25.3,101601,185.0,21.6,3,101.0,...,24.0,14.0,11.0,4.0,8.0,77.0,468.0,212.0,116.0,3
3,32.0,19910107,101117,180.0,25.8,101332,173.0,23.8,3,108.0,...,38.0,15.0,13.0,8.0,12.0,65.0,502.0,72.0,483.0,3
4,32.0,19910107,101901,185.0,19.7,101735,196.0,20.6,3,65.0,...,21.0,12.0,9.0,4.0,6.0,190.0,142.0,28.0,876.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89201,4.0,20240203,105430,175.0,34.2,212051,NaN,18.8,3,81.0,...,13.0,6.0,8.0,0.0,6.0,136.0,489.0,1109.0,8.0,2
89202,4.0,20240203,105430,175.0,34.2,208364,185.0,23.9,3,95.0,...,33.0,6.0,8.0,6.0,11.0,136.0,489.0,616.0,55.0,2
89203,4.0,20240203,212051,NaN,18.8,209943,NaN,21.8,3,77.0,...,17.0,7.0,6.0,8.0,14.0,1109.0,8.0,740.0,34.0,2
89204,4.0,20240202,122533,NaN,26.9,202475,NaN,23.2,3,131.0,...,25.0,6.0,9.0,1.0,4.0,554.0,67.0,748.0,32.0,2
89205,4.0,20240202,122533,NaN,26.9,144748,NaN,27.3,3,159.0,...,32.0,17.0,14.0,5.0,9.0,554.0,67.0,416.0,109.0,3

In [368]:
df_num.describe()

,draw_size,tourney_date,winner_id,winner_ht,winner_age,loser_id,loser_ht,loser_age,best_of,minutes,...,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,sets
count,89206.000000,8.920600e+04,89206.000000,88743.000000,89206.000000,89206.000000,87975.000000,89199.000000,89206.000000,89206.000000,...,89190.000000,89190.00000,89190.000000,89190.000000,89190.000000,89206.000000,89206.000000,89206.000000,89206.000000,89206.000000
mean,57.353429,2.006554e+07,107596.367699,185.832809,25.914112,107494.733291,185.267928,26.066929,3.331278,105.489261,...,32.124700,15.05412,12.275188,4.825395,8.753414,63.368910,1492.328633,98.753044,926.588279,2.577697
std,36.810125,9.673286e+04,17804.476225,6.652298,3.794761,17542.079521,6.607985,3.879360,0.743517,38.751093,...,14.058613,7.07757,3.992722,3.256168,4.083305,81.640095,1774.401095,128.656639,1009.267268,0.737696
min,2.000000,1.991011e+07,100284.000000,168.000000,15.800000,100282.000000,160.000000,15.400000,3.000000,26.000000,...,0.000000,0.00000,0.000000,-6.000000,0.000000,1.000000,1.000000,1.000000,1.000000,2.000000
25%,32.000000,1.998062e+07,102202.000000,183.000000,23.100000,102202.000000,180.000000,23.200000,3.000000,76.000000,...,22.000000,10.00000,9.000000,2.000000,6.000000,17.000000,574.000000,36.000000,427.000000,2.000000
50%,32.000000,2.006061e+07,103720.000000,185.000000,25.600000,103602.000000,185.000000,25.800000,3.000000,98.000000,...,30.000000,14.00000,11.000000,4.000000,8.000000,44.000000,915.000000,68.000000,681.000000,2.000000
75%,64.000000,2.015012e+07,104918.000000,190.000000,28.400000,104926.000000,190.000000,28.600000,3.000000,127.000000,...,40.000000,19.00000,15.000000,7.000000,11.000000,82.000000,1665.000000,111.000000,1055.000000,3.000000
max,128.000000,2.024052e+07,212051.000000,211.000000,42.300000,212203.000000,211.000000,44.000000,5.000000,345.000000,...,145.000000,66.00000,41.000000,27.000000,38.000000,1890.000000,16950.000000,2159.000000,16950.000000,5.000000

In [369]:
df_num.isnull().sum()

draw_size                0
tourney_date             0
winner_id                0
winner_ht              463
winner_age               0
loser_id                 0
loser_ht              1231
loser_age                7
best_of                  0
minutes                  0
w_ace                   16
w_df                    16
w_svpt                  16
w_1stIn                 16
w_1stWon                16
w_2ndWon                16
w_SvGms                 16
w_bpSaved               16
w_bpFaced               16
l_ace                   16
l_df                    16
l_svpt                  16
l_1stIn                 16
l_1stWon                16
l_2ndWon                16
l_SvGms                 16
l_bpSaved               16
l_bpFaced               16
winner_rank              0
winner_rank_points       0
loser_rank               0
loser_rank_points        0
sets                     0
dtype: int64

In [370]:
    #imputar NaN con la media en : winner_ht,winner_age,loser_ht,loser_age 
columns=['winner_ht','winner_age','loser_ht','loser_age']

imputer = SimpleImputer (missing_values=np.nan, strategy="mean")

df_num[columns] = imputer.fit_transform(df_num[columns])

df_num

,draw_size,tourney_date,winner_id,winner_ht,winner_age,loser_id,loser_ht,loser_age,best_of,minutes,...,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,sets
0,32.0,19910107,101142,180.000000,25.6,101746,175.000000,20.6,3,63.0,...,17.0,7.0,8.0,2.0,6.0,9.0,1487.0,78.0,459.0,2
1,32.0,19910107,101613,180.000000,21.5,100587,188.000000,31.8,3,72.0,...,22.0,6.0,8.0,7.0,11.0,94.0,371.0,220.0,114.0,2
2,32.0,19910107,101179,185.000000,25.3,101601,185.000000,21.6,3,101.0,...,24.0,14.0,11.0,4.0,8.0,77.0,468.0,212.0,116.0,3
3,32.0,19910107,101117,180.000000,25.8,101332,173.000000,23.8,3,108.0,...,38.0,15.0,13.0,8.0,12.0,65.0,502.0,72.0,483.0,3
4,32.0,19910107,101901,185.000000,19.7,101735,196.000000,20.6,3,65.0,...,21.0,12.0,9.0,4.0,6.0,190.0,142.0,28.0,876.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89201,4.0,20240203,105430,175.000000,34.2,212051,185.267928,18.8,3,81.0,...,13.0,6.0,8.0,0.0,6.0,136.0,489.0,1109.0,8.0,2
89202,4.0,20240203,105430,175.000000,34.2,208364,185.000000,23.9,3,95.0,...,33.0,6.0,8.0,6.0,11.0,136.0,489.0,616.0,55.0,2
89203,4.0,20240203,212051,185.832809,18.8,209943,185.267928,21.8,3,77.0,...,17.0,7.0,6.0,8.0,14.0,1109.0,8.0,740.0,34.0,2
89204,4.0,20240202,122533,185.832809,26.9,202475,185.267928,23.2,3,131.0,...,25.0,6.0,9.0,1.0,4.0,554.0,67.0,748.0,32.0,2
89205,4.0,20240202,122533,185.832809,26.9,144748,185.267928,27.3,3,159.0,...,32.0,17.0,14.0,5.0,9.0,554.0,67.0,416.0,109.0,3

In [371]:
df.isnull().sum()

tourney_name             0
surface                  0
draw_size                0
tourney_level            0
tourney_date             0
winner_id                0
winner_name              0
winner_hand              0
winner_ht              463
winner_ioc               0
winner_age               0
loser_id                 0
loser_name               0
loser_hand               5
loser_ht              1231
loser_ioc                0
loser_age                7
score                    0
best_of                  0
round                    0
minutes                  0
w_ace                   16
w_df                    16
w_svpt                  16
w_1stIn                 16
w_1stWon                16
w_2ndWon                16
w_SvGms                 16
w_bpSaved               16
w_bpFaced               16
l_ace                   16
l_df                    16
l_svpt                  16
l_1stIn                 16
l_1stWon                16
l_2ndWon                16
l_SvGms                 16
l_bpSaved               16
l_bpFaced               16
winner_rank              0
winner_rank_points       0
loser_rank               0
loser_rank_points        0
sets                     0
dtype: int64

In [372]:
    #imputar NaN con el más frecuente en: w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced
columns=['w_ace','w_df','w_svpt','w_1stIn','w_1stWon','w_2ndWon','w_SvGms','w_bpSaved','w_bpFaced',
         'l_ace','l_df','l_svpt','l_1stIn','l_1stWon','l_2ndWon','l_SvGms','l_bpSaved','l_bpFaced']

imputer = SimpleImputer (missing_values=np.nan, strategy="most_frequent")

df_num[columns] = imputer.fit_transform(df_num[columns])

df_num

,draw_size,tourney_date,winner_id,winner_ht,winner_age,loser_id,loser_ht,loser_age,best_of,minutes,...,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,sets
0,32.0,19910107,101142,180.000000,25.6,101746,175.000000,20.6,3,63.0,...,17.0,7.0,8.0,2.0,6.0,9.0,1487.0,78.0,459.0,2
1,32.0,19910107,101613,180.000000,21.5,100587,188.000000,31.8,3,72.0,...,22.0,6.0,8.0,7.0,11.0,94.0,371.0,220.0,114.0,2
2,32.0,19910107,101179,185.000000,25.3,101601,185.000000,21.6,3,101.0,...,24.0,14.0,11.0,4.0,8.0,77.0,468.0,212.0,116.0,3
3,32.0,19910107,101117,180.000000,25.8,101332,173.000000,23.8,3,108.0,...,38.0,15.0,13.0,8.0,12.0,65.0,502.0,72.0,483.0,3
4,32.0,19910107,101901,185.000000,19.7,101735,196.000000,20.6,3,65.0,...,21.0,12.0,9.0,4.0,6.0,190.0,142.0,28.0,876.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89201,4.0,20240203,105430,175.000000,34.2,212051,185.267928,18.8,3,81.0,...,13.0,6.0,8.0,0.0,6.0,136.0,489.0,1109.0,8.0,2
89202,4.0,20240203,105430,175.000000,34.2,208364,185.000000,23.9,3,95.0,...,33.0,6.0,8.0,6.0,11.0,136.0,489.0,616.0,55.0,2
89203,4.0,20240203,212051,185.832809,18.8,209943,185.267928,21.8,3,77.0,...,17.0,7.0,6.0,8.0,14.0,1109.0,8.0,740.0,34.0,2
89204,4.0,20240202,122533,185.832809,26.9,202475,185.267928,23.2,3,131.0,...,25.0,6.0,9.0,1.0,4.0,554.0,67.0,748.0,32.0,2
89205,4.0,20240202,122533,185.832809,26.9,144748,185.267928,27.3,3,159.0,...,32.0,17.0,14.0,5.0,9.0,554.0,67.0,416.0,109.0,3

In [373]:
df_num.isnull().sum()

draw_size             0
tourney_date          0
winner_id             0
winner_ht             0
winner_age            0
loser_id              0
loser_ht              0
loser_age             0
best_of               0
minutes               0
w_ace                 0
w_df                  0
w_svpt                0
w_1stIn               0
w_1stWon              0
w_2ndWon              0
w_SvGms               0
w_bpSaved             0
w_bpFaced             0
l_ace                 0
l_df                  0
l_svpt                0
l_1stIn               0
l_1stWon              0
l_2ndWon              0
l_SvGms               0
l_bpSaved             0
l_bpFaced             0
winner_rank           0
winner_rank_points    0
loser_rank            0
loser_rank_points     0
sets                  0
dtype: int64

In [374]:
#faltan los nulos de ranking que como no se pueden imputar por no ser real, BORRAR EN LA PARTE DE GENÉRICAS

# CATEGÓRICAS

In [375]:
    #df de variables categóricas
df_cat = df.drop(columns=df_num.columns)
df_cat

,tourney_name,surface,tourney_level,winner_name,winner_hand,winner_ioc,loser_name,loser_hand,loser_ioc,score,round
0,Auckland,Hard,A,Emilio Sanchez,R,ESP,Renzo Furlan,R,ITA,6-4 6-1,R32
1,Auckland,Hard,A,Malivai Washington,R,USA,Steve Guy,R,NZL,6-3 6-2,R32
2,Auckland,Hard,A,Jean Philippe Fleurian,R,FRA,Brett Steven,R,NZL,2-6 6-1 6-2,R32
3,Auckland,Hard,A,Eric Jelen,R,GER,Gilad Bloom,L,ISR,6-3 1-6 6-4,R32
4,Auckland,Hard,A,Chuck Adams,R,USA,Richard Fromberg,R,AUS,6-3 6-4,R32
...,...,...,...,...,...,...,...,...,...,...,...
89201,Davis Cup WG2 PO: URU vs MDA,Clay,D,Radu Albot,R,MDA,Joaquin Aguilar Cardozo,U,URU,6-2 6-3,RR
89202,Davis Cup WG2 PO: URU vs MDA,Clay,D,Radu Albot,R,MDA,Franco Roncadelli,L,URU,6-3 6-1,RR
89203,Davis Cup WG2 PO: URU vs MDA,Clay,D,Joaquin Aguilar Cardozo,U,URU,Ilya Snitari,U,MDA,6-1 6-0,RR
89204,Davis Cup WG2 PO: VIE vs RSA,Hard,D,Nam Hoang Ly,R,VIE,Philip Henning,R,RSA,6-3 6-4,RR
89205,Davis Cup WG2 PO: VIE vs RSA,Hard,D,Nam Hoang Ly,R,VIE,Kris Van Wyk,U,RSA,6-4 3-6 6-3,RR

In [376]:
   df_cat.isnull().sum()

tourney_name     0
surface          0
tourney_level    0
winner_name      0
winner_hand      0
winner_ioc       0
loser_name       0
loser_hand       5
loser_ioc        0
score            0
round            0
dtype: int64

In [377]:
    # cuáles son los faltantes
df_cat[df_cat['loser_hand'].isna()]

,tourney_name,surface,tourney_level,winner_name,winner_hand,winner_ioc,loser_name,loser_hand,loser_ioc,score,round
68595,Davis Cup G1 R1: CHI vs DOM,Clay,D,Hans Podlipnik Castillo,R,CHI,Jose Olivares,NaN,DOM,6-1 6-1 7-6(4),RR
68597,Davis Cup G1 R1: CHI vs DOM,Clay,D,Gonzalo Lama,R,CHI,Jose Olivares,NaN,DOM,6-4 6-0,RR
71022,Davis Cup G1 R1: DOM vs CHI,Hard,D,Tomas Barrios Vera,R,CHI,Jose Olivares,NaN,DOM,7-6(8) 7-6(2),RR
73776,Davis Cup G2 R1: THA vs SRI,Clay,D,Wishaya Trongcharoenchaikul,R,THA,Yasitha De Silva,NaN,SRI,6-3 6-3,RR
73777,Davis Cup G2 R1: THA vs SRI,Clay,D,Jirat Navasirisomboon,R,THA,Yasitha De Silva,NaN,SRI,7-5 6-2,RR

In [378]:
players = pd.read_csv('atp_players.csv')

    # comprobación de si los nulos de loser_hand están en otro csv: players.csv
# 1º: Jose Olivares
players[(players['name_first']=='Jose') & (players['name_last']=='Olivares')]

,player_id,name_first,name_last,hand,dob,ioc,height,wikidata_id
44757,144773,Jose,Olivares,R,19970108.0,DOM,NaN,Q28674954

In [379]:
# 2º: Yasitha De Silva
players[(players['name_first']=='Yasitha') & (players['name_last']=='De Silva')]

,player_id,name_first,name_last,hand,dob,ioc,height,wikidata_id
54565,202462,Yasitha,De Silva,R,19950703.0,SRI,NaN,NaN

In [380]:
    #1er nan de loser_hand (para indices)
df_cat[df_cat['loser_name']=='Jose Olivares']

,tourney_name,surface,tourney_level,winner_name,winner_hand,winner_ioc,loser_name,loser_hand,loser_ioc,score,round
68595,Davis Cup G1 R1: CHI vs DOM,Clay,D,Hans Podlipnik Castillo,R,CHI,Jose Olivares,NaN,DOM,6-1 6-1 7-6(4),RR
68597,Davis Cup G1 R1: CHI vs DOM,Clay,D,Gonzalo Lama,R,CHI,Jose Olivares,NaN,DOM,6-4 6-0,RR
71022,Davis Cup G1 R1: DOM vs CHI,Hard,D,Tomas Barrios Vera,R,CHI,Jose Olivares,NaN,DOM,7-6(8) 7-6(2),RR

In [381]:
    # imputar valor de loser_hand a los faltantes 
df_cat.loc[68595,'loser_hand']='R'
df_cat.loc[68597,'loser_hand']='R'
df_cat.loc[71022,'loser_hand']='R'
    # comprobar imputación
df_cat[df_cat['loser_name']=='Jose Olivares']

,tourney_name,surface,tourney_level,winner_name,winner_hand,winner_ioc,loser_name,loser_hand,loser_ioc,score,round
68595,Davis Cup G1 R1: CHI vs DOM,Clay,D,Hans Podlipnik Castillo,R,CHI,Jose Olivares,R,DOM,6-1 6-1 7-6(4),RR
68597,Davis Cup G1 R1: CHI vs DOM,Clay,D,Gonzalo Lama,R,CHI,Jose Olivares,R,DOM,6-4 6-0,RR
71022,Davis Cup G1 R1: DOM vs CHI,Hard,D,Tomas Barrios Vera,R,CHI,Jose Olivares,R,DOM,7-6(8) 7-6(2),RR

In [382]:
    #siguiente nan de loser_hand (para indices)
df_cat[df_cat['loser_name']=='Yasitha De Silva']

,tourney_name,surface,tourney_level,winner_name,winner_hand,winner_ioc,loser_name,loser_hand,loser_ioc,score,round
73776,Davis Cup G2 R1: THA vs SRI,Clay,D,Wishaya Trongcharoenchaikul,R,THA,Yasitha De Silva,NaN,SRI,6-3 6-3,RR
73777,Davis Cup G2 R1: THA vs SRI,Clay,D,Jirat Navasirisomboon,R,THA,Yasitha De Silva,NaN,SRI,7-5 6-2,RR

In [383]:
    #imputaciñon de valores a loser_hand con nan
df_cat.loc[73776,'loser_hand']='R'
df_cat.loc[73777,'loser_hand']='R'
df_cat[df_cat['loser_name']=='Yasitha De Silva']

,tourney_name,surface,tourney_level,winner_name,winner_hand,winner_ioc,loser_name,loser_hand,loser_ioc,score,round
73776,Davis Cup G2 R1: THA vs SRI,Clay,D,Wishaya Trongcharoenchaikul,R,THA,Yasitha De Silva,R,SRI,6-3 6-3,RR
73777,Davis Cup G2 R1: THA vs SRI,Clay,D,Jirat Navasirisomboon,R,THA,Yasitha De Silva,R,SRI,7-5 6-2,RR

In [384]:
df_cat.isnull().sum() #limpio,sin nulos

tourney_name     0
surface          0
tourney_level    0
winner_name      0
winner_hand      0
winner_ioc       0
loser_name       0
loser_hand       0
loser_ioc        0
score            0
round            0
dtype: int64

In [385]:
df_cat.tourney_level.unique()

array(['A', 'G', 'M', 'F', 'D'], dtype=object)

## Limpieza de ROUND

In [386]:
   # limpiar round para que sea numerica 
df_cat['round'].unique()
# R32:32,R16:16,QF:8,SF:4,F:2,BR:128

array(['R32', 'R16', 'QF', 'SF', 'F', 'R128', 'R64', 'RR', 'ER', 'BR'],
      dtype=object)

In [387]:
df_cat['round'].value_counts()

round
R32     31713
R16     16849
R64     14713
R128     8960
QF       8441
SF       4324
F        2228
RR       1945
ER         32
BR          1
Name: count, dtype: int64

In [388]:
    # quitar la R a las rondas que tienen numero 
rondas = {'R32':32,'R16':16,'QF':8,'SF':4,'F':2,'R128':128,'R64':64,}
df_cat['round'] = df_cat['round'].map(rondas).fillna(df_cat['round'])
df_cat['round'].unique()

array([32.0, 16.0, 8.0, 4.0, 2.0, 128.0, 64.0, 'RR', 'ER', 'BR'],
      dtype=object)

In [389]:
    #ver donde están BR
df_cat[df_cat['round']=='BR']

,tourney_name,surface,tourney_level,winner_name,winner_hand,winner_ioc,loser_name,loser_hand,loser_ioc,score,round
70096,Rio Olympics,Hard,A,Kei Nishikori,R,JPN,Rafael Nadal,L,ESP,6-2 6-7(1) 6-3,BR

In [390]:
    #ver cuantas rondas tiene Rio Olympics para saber que valor darle a BR
df[df['tourney_name']=='Rio Olympics'][['draw_size','round']].value_counts()

draw_size  round
64.0       R64      30
           R32      15
           R16       8
           QF        4
           SF        2
           BR        1
           F         1
Name: count, dtype: int64

In [391]:
    #buscar BR 
df_cat[(df_cat['tourney_name']=='Rio Olympics') & (df_cat['round']=='BR')]

,tourney_name,surface,tourney_level,winner_name,winner_hand,winner_ioc,loser_name,loser_hand,loser_ioc,score,round
70096,Rio Olympics,Hard,A,Kei Nishikori,R,JPN,Rafael Nadal,L,ESP,6-2 6-7(1) 6-3,BR

In [392]:
   #imputar a BR=128
df_cat.loc[70096,'round']=128

    #comprobar imputación
df_cat[df_cat['tourney_name']=='Rio Olympics']['round'].value_counts()
df_cat[df_cat['tourney_name']=='Rio Olympics']['round'].unique()
df_cat['round'].unique()

array([32.0, 16.0, 8.0, 4.0, 2.0, 128.0, 64.0, 'RR', 'ER'], dtype=object)

In [393]:
    # Buscar donde estan ER
df_cat[df_cat['round']=='ER']

    # cuantos ER hay (32)
df_cat[df_cat['round']=='ER'].shape

    #que torneos tienen ER
df[df['round']=='ER']['tourney_name'].unique()

    #lista con los nombres de los torneos que tienen ER
RR_torneoER = list(df[df['round']=='ER']['tourney_name'].unique())
RR_torneoER

['Adelaide', 'Las Vegas', 'Delray Beach', 'Buenos Aires']

In [394]:
    # que rondas hay en cada uno de los 4 torneos con ER
df_cat[df_cat['tourney_name']=='Adelaide']['round'].unique()

array([32.0, 16.0, 8.0, 4.0, 2.0, 'ER', 'RR'], dtype=object)

In [395]:
df_cat[df_cat['tourney_name']=='Las Vegas']['round'].unique()

array([32.0, 16.0, 8.0, 4.0, 2.0, 'ER', 'RR'], dtype=object)

In [396]:
df_cat[df_cat['tourney_name']=='Delray Beach']['round'].unique()

array([32.0, 16.0, 8.0, 4.0, 2.0, 'ER', 'RR'], dtype=object)

In [397]:
df_cat[df_cat['tourney_name']=='Buenos Aires']['round'].unique()

array([32.0, 16.0, 8.0, 4.0, 2.0, 'ER', 'RR'], dtype=object)

In [398]:
    # lista los indices de las filas que contienen ER 
indices = list(df_cat[df_cat['round'] == 'ER'].index)
indices

[46605,
 46606,
 46607,
 46608,
 46609,
 46610,
 46611,
 46612,
 47531,
 47532,
 47533,
 47534,
 47535,
 47536,
 47537,
 47538,
 47802,
 47803,
 47804,
 47805,
 47806,
 47807,
 47808,
 47809,
 47869,
 47870,
 47871,
 47872,
 47873,
 47874,
 47875,
 47876]

In [399]:
   # cambiamos los ER=64
df_cat.loc[indices,'round'] = 64

    #comprobación de la imputación
df_cat['round'].unique()

array([32.0, 16.0, 8.0, 4.0, 2.0, 128.0, 64.0, 'RR'], dtype=object)

In [400]:
    # TORNEOS QUE TENIAN ER y RR
RR_torneoER

['Adelaide', 'Las Vegas', 'Delray Beach', 'Buenos Aires']

In [401]:
    # comprobación de como se sacarían los indices de uno
list(df_cat[(df_cat['tourney_name']=='Adelaide') & (df_cat['round']=='RR')].index)

[46613,
 46614,
 46615,
 46616,
 46617,
 46618,
 46619,
 46620,
 46621,
 46622,
 46623,
 46624,
 46625,
 46626,
 46627,
 46628,
 46629,
 46630,
 46631,
 46632,
 46633,
 46634,
 46635]

In [402]:
    # lista de listas de los indices de las filas con RR de los torneos que tenian ER y RR 
indices_RR = []
for i in RR_torneoER:
     indices_RR.append(list(df_cat[(df_cat['tourney_name']==i) & (df_cat['round']=='RR')].index))
len(indices_RR)

4

In [403]:
    #lista unica de indices_RR
import itertools
RR_indices = list(itertools.chain(*indices_RR))
len(RR_indices)

93

In [404]:
    # imputacion RR=128
df_cat.loc[RR_indices,'round'] =128

    #comprobación de la imputacion
for i in RR_torneoER:
     print(df_cat[df_cat['tourney_name']==i]['round'].unique())

[32.0 16.0 8.0 4.0 2.0 64 128]
[32.0 16.0 8.0 4.0 2.0 64 128]
[32.0 16.0 8.0 4.0 2.0 64 128]
[32.0 16.0 8.0 4.0 2.0 64 128]

In [405]:
    # Bucar los RR que faltan por imputar
df_cat[df_cat['round']=='RR']
df_cat[df_cat['round']=='RR']['tourney_name'].unique()  
# Faltan 'Tour Finals', 'Dusseldorf', 'Masters Cup', COPA DAVIS

array(['Tour Finals', 'Dusseldorf', 'Masters Cup',
       'Davis Cup G1 R1: BAR vs ECU', 'Davis Cup G1 R1: CHI vs DOM',
       'Davis Cup G1 R1: HUN vs ISR', 'Davis Cup G1 R1: NZL vs KOR',
       'Davis Cup G1 R1: PAK vs CHN', 'Davis Cup G1 R1: POR vs AUT',
       'Davis Cup G1 R1: ROU vs SLO', 'Davis Cup G1 R1: RUS vs SWE',
       'Davis Cup G2 R1: BIH vs TUN', 'Davis Cup G2 R1: BUL vs TUR',
       'Davis Cup G2 R1: EGY vs BLR', 'Davis Cup G2 R1: GEO vs DEN',
       'Davis Cup G2 R1: LTU vs NOR', 'Davis Cup G2 R1: MEX vs GUA',
       'Davis Cup G2 R1: MON vs LAT', 'Davis Cup G2 R1: PHI vs KUW',
       'Davis Cup G2 R1: RSA vs LUX', 'Davis Cup G2 R1: SRI vs THA',
       'Davis Cup G2 R1: VIE vs INA', 'Davis Cup G2 R1: ZIM vs FIN',
       'Davis Cup WG R1: ARG vs POL', 'Davis Cup WG R1: CAN vs FRA',
       'Davis Cup WG R1: CRO vs BEL', 'Davis Cup WG R1: GBR vs JPN',
       'Davis Cup WG R1: GER vs CZE', 'Davis Cup WG R1: SRB vs KAZ',
       'Davis Cup WG R1: SUI vs ITA', 'Davis Cup WG R1: USA vs AUS',
       'Davis Cup G1 R2: BRA vs ECU', 'Davis Cup G1 R2: CHI vs COL',
       'Davis Cup G1 R2: CHN vs UZB', 'Davis Cup G1 R2: ESP vs ROU',
       'Davis Cup G1 R2: HUN vs SVK', 'Davis Cup G1 R2: IND vs KOR',
       'Davis Cup G1 R2: RUS vs NED', 'Davis Cup G1 R2: UKR vs AUT',
       'Davis Cup G2 R2: ESA vs VEN', 'Davis Cup G2 R2: FIN vs DEN',
       'Davis Cup G2 R2: LAT vs BLR', 'Davis Cup G2 R2: LTU vs RSA',
       'Davis Cup G2 R2: PER vs MEX', 'Davis Cup G2 R2: TPE vs PHI',
       'Davis Cup G2 R2: TUR vs BIH', 'Davis Cup WG QF: FRA vs CZE',
       'Davis Cup WG QF: GBR vs SRB', 'Davis Cup WG QF: ITA vs ARG',
       'Davis Cup WG QF: USA vs CRO', 'Davis Cup G2 R3: BLR vs DEN',
       'Davis Cup G2 R3: LTU vs BIH', 'Davis Cup G2 R3: PER vs VEN',
       'Davis Cup G2 R3: TPE vs THA', 'Davis Cup WG PO: AUS vs SVK',
       'Davis Cup WG PO: BEL vs BRA', 'Davis Cup WG PO: CAN vs CHI',
       'Davis Cup WG PO: ESP vs IND', 'Davis Cup WG PO: GER vs POL',
       'Davis Cup WG PO: JPN vs UKR', 'Davis Cup WG PO: KAZ vs RUS',
       'Davis Cup WG PO: SUI vs UZB', 'Davis Cup WG SF: FRA vs CRO',
       'Davis Cup WG SF: GBR vs ARG', 'Davis Cup WG F: ARG vs CRO',
       'Davis Cup G1 R1: DOM vs CHI', 'Davis Cup G1 R1: ISR vs POR',
       'Davis Cup G1 R1: NZL vs IND', 'Davis Cup G1 R1: PER vs ECU',
       'Davis Cup G1 R1: POL vs BIH', 'Davis Cup G1 R1: ROU vs BLR',
       'Davis Cup G1 R1: UZB vs KOR', 'Davis Cup G1 R2: SVK vs HUN',
       'Davis Cup G2 R1: BOL vs ESA', 'Davis Cup G2 R1: EST vs RSA',
       'Davis Cup G2 R1: FIN vs GEO', 'Davis Cup G2 R1: INA vs PHI',
       'Davis Cup G2 R1: KUW vs THA', 'Davis Cup G2 R1: MAR vs DEN',
       'Davis Cup G2 R1: MON vs SLO', 'Davis Cup G2 R1: NOR vs LAT',
       'Davis Cup G2 R1: SWE vs TUN', 'Davis Cup G2 R1: TUR vs CYP',
       'Davis Cup G2 R1: VIE vs HKG', 'Davis Cup WG R1: ARG vs ITA',
       'Davis Cup WG R1: BEL vs GER', 'Davis Cup WG R1: CAN vs GBR',
       'Davis Cup WG R1: CZE vs AUS', 'Davis Cup WG R1: ESP vs CRO',
       'Davis Cup WG R1: JPN vs FRA', 'Davis Cup WG R1: RUS vs SRB',
       'Davis Cup WG R1: SUI vs USA', 'Davis Cup G1 R1: TPE vs CHN',
       'Davis Cup G1 R2: BLR vs AUT', 'Davis Cup G1 R2: KAZ vs CHN',
       'Davis Cup G1 R2: NED vs BIH', 'Davis Cup G1 R2: POR vs UKR',
       'Davis Cup G1 R2: UZB vs IND', 'Davis Cup G2 R2: BAR vs GUA',
       'Davis Cup G2 R2: LTU vs GEO', 'Davis Cup G2 R2: NOR vs DEN',
       'Davis Cup G2 R2: RSA vs SLO', 'Davis Cup G2 R2: SWE vs TUR',
       'Davis Cup WG QF: AUS vs USA', 'Davis Cup WG QF: FRA vs GBR',
       'Davis Cup WG QF: ITA vs BEL', 'Davis Cup WG QF: SRB vs ESP',
       'Davis Cup G2 R3: BAR vs VEN', 'Davis Cup G2 R3: DEN vs RSA',
       'Davis Cup G2 R3: SWE vs LTU', 'Davis Cup WG PO: ARG vs KAZ',
       'Davis Cup WG PO: CAN vs IND', 'Davis Cup WG PO: CRO vs COL',
       'Davis Cup WG PO: CZE vs NED', 'Davis Cup WG PO: GER vs POR',
       'Davis Cup WG PO: JPN vs BRA', 'Davis Cup WG PO: RUS vs HUN',
       'Davis Cup WG PO: SUI vs BLR', 'Davis Cup WG SF: BEL vs AUS',
       'Davis Cup WG SF: FRA vs SRB', 'Davis Cup WG F: BEL vs FRA',
       'Davis Cup G1 R1: AUT vs BLR', 'Davis Cup G1 R1: CHI vs ECU',
       'Davis Cup G1 R1: CHN vs NZL', 'Davis Cup G1 R1: COL vs BAR',
       'Davis Cup G1 R1: DOM vs BRA', 'Davis Cup G1 R1: KOR vs PAK',
       'Davis Cup G1 R1: RSA vs ISR', 'Davis Cup G1 R1: UKR vs SWE',
       'Davis Cup WG R1: AUS vs GER', 'Davis Cup WG R1: CAN vs CRO',
       'Davis Cup WG R1: FRA vs NED', 'Davis Cup WG R1: GBR vs ESP',
       'Davis Cup WG R1: HUN vs BEL', 'Davis Cup WG R1: ITA vs JPN',
       'Davis Cup WG R1: KAZ vs SUI', 'Davis Cup WG R1: USA vs SRB',
       'Davis Cup G2 R1: BOL vs PER', 'Davis Cup G2 R1: EGY vs NOR',
       'Davis Cup G2 R1: ESA vs URU', 'Davis Cup G2 R1: EST vs LTU',
       'Davis Cup G2 R1: GEO vs MAR', 'Davis Cup G2 R1: IRI vs HKG',
       'Davis Cup G2 R1: IRL vs DEN', 'Davis Cup G2 R1: LBN vs TPE',
       'Davis Cup G2 R1: PHI vs INA', 'Davis Cup G2 R1: SLO vs POL',
       'Davis Cup G2 R1: THA vs SRI', 'Davis Cup G2 R1: TUN vs FIN',
       'Davis Cup G2 R1: TUR vs ZIM', 'Davis Cup G2 R1: VEN vs GUA',
       'Davis Cup G1 R2: ARG vs CHI', 'Davis Cup G1 R2: AUT vs RUS',
       'Davis Cup G1 R2: BIH vs SVK', 'Davis Cup G1 R2: COL vs BRA',
       'Davis Cup G1 R2: CZE vs ISR', 'Davis Cup G1 R2: IND vs CHN',
       'Davis Cup G1 R2: PAK vs UZB', 'Davis Cup G1 R2: POR vs SWE',
       'Davis Cup WG QF: ESP vs GER', 'Davis Cup WG QF: FRA vs ITA',
       'Davis Cup WG QF: KAZ vs CRO', 'Davis Cup WG QF: USA vs BEL',
       'Davis Cup G2 R2: EGY vs DEN', 'Davis Cup G2 R2: FIN vs LTU',
       'Davis Cup G2 R2: HKG vs LBN', 'Davis Cup G2 R2: MEX vs PER',
       'Davis Cup G2 R2: POL vs ZIM', 'Davis Cup G2 R2: ROU vs MAR',
       'Davis Cup G2 R2: THA vs PHI', 'Davis Cup G2 R2: VEN vs URU',
       'Davis Cup G2 R3: EGY vs FIN', 'Davis Cup WG PO: ARG vs COL',
       'Davis Cup WG PO: AUT vs AUS', 'Davis Cup WG PO: CAN vs NED',
       'Davis Cup WG PO: GBR vs UZB', 'Davis Cup WG PO: HUN vs CZE',
       'Davis Cup WG PO: JPN vs BIH', 'Davis Cup WG PO: SRB vs IND',
       'Davis Cup WG PO: SUI vs SWE', 'Davis Cup WG SF: CRO vs USA',
       'Davis Cup WG SF: FRA vs ESP', 'Davis Cup G2 R3: ROU vs POL',
       'Davis Cup G2 R3: THA vs LBN', 'Davis Cup G2 R3: URU vs MEX',
       'Davis Cup WG F: FRA vs CRO', 'Davis Cup Finals RR: FRA vs JPN',
       'Davis Cup Finals RR: FRA vs SRB',
       'Davis Cup Finals RR: SRB vs JPN',
       'Davis Cup Finals RR: CRO vs ESP',
       'Davis Cup Finals RR: CRO vs RUS',
       'Davis Cup Finals RR: ESP vs RUS',
       'Davis Cup Finals RR: ARG vs CHI',
       'Davis Cup Finals RR: ARG vs GER',
       'Davis Cup Finals RR: GER vs CHI',
       'Davis Cup Finals RR: AUS vs COL',
       'Davis Cup Finals RR: BEL vs AUS',
       'Davis Cup Finals RR: BEL vs COL',
       'Davis Cup Finals RR: GBR vs KAZ',
       'Davis Cup Finals RR: GBR vs NED',
       'Davis Cup Finals RR: KAZ vs NED',
       'Davis Cup Finals RR: ITA vs CAN',
       'Davis Cup Finals RR: USA vs CAN',
       'Davis Cup Finals RR: USA vs ITA',
       'Davis Cup Finals QF: ARG vs ESP',
       'Davis Cup Finals QF: AUS vs CAN',
       'Davis Cup Finals F: CAN vs ESP',
       'Davis Cup Finals SF: GBR vs ESP',
       'Davis Cup Finals QF: GBR vs GER',
       'Davis Cup Finals SF: RUS vs CAN',
       'Davis Cup Finals QF: SRB vs RUS', 'Davis Cup QLS R1: AUS vs BIH',
       'Davis Cup QLS R1: AUT vs CHI', 'Davis Cup QLS R1: BEL vs BRA',
       'Davis Cup QLS R1: CAN vs SVK', 'Davis Cup QLS R1: CZE vs NED',
       'Davis Cup QLS R1: GER vs HUN', 'Davis Cup QLS R1: ITA vs IND',
       'Davis Cup QLS R1: JPN vs CHN', 'Davis Cup QLS R1: KAZ vs POR',
       'Davis Cup QLS R1: SRB vs UZB', 'Davis Cup QLS R1: SUI vs RUS',
       'Davis Cup QLS R1: SWE vs COL', 'Atp Cup',
       'Davis Cup QLS R1: ARG vs COL', 'Davis Cup QLS R1: AUS vs BRA',
       'Davis Cup QLS R1: AUT vs URU', 'Davis Cup QLS R1: BEL vs HUN',
       'Davis Cup QLS R1: CRO vs IND', 'Davis Cup QLS R1: CZE vs SVK',
       'Davis Cup QLS R1: GER vs BLR', 'Davis Cup QLS R1: JPN vs ECU',
       'Davis Cup QLS R1: KAZ vs NED', 'Davis Cup QLS R1: SWE vs CHI',
       'Davis Cup QLS R1: USA vs UZB', 'Davis Cup WG1 PO: BIH vs RSA',
       'Davis Cup WG1 PO: BOL vs DOM', 'Davis Cup WG1 PO: LBN vs THA',
       'Davis Cup WG1 PO: LTU vs POR', 'Davis Cup WG1 PO: MEX vs FIN',
       'Davis Cup WG1 PO: NOR vs BAR', 'Davis Cup WG1 PO: PER vs SUI',
       'Davis Cup WG1 PO: TUR vs ISR', 'Davis Cup WG1 PO: UKR vs TPE',
       'Davis Cup WG1 PO: VEN vs NZL', 'Davis Cup Finals RR: ESP vs ECU',
       'Davis Cup Finals RR: ESP vs RTF',
       'Davis Cup Finals RR: RTF vs ECU',
       'Davis Cup Finals RR: CAN vs KAZ',
       'Davis Cup Finals RR: CAN vs SWE',
       'Davis Cup Finals RR: KAZ vs SWE',
       'Davis Cup Finals RR: FRA vs CZE',
       'Davis Cup Finals RR: FRA vs GBR',
       'Davis Cup Finals RR: GBR vs CZE',
       'Davis Cup Finals RR: AUS vs HUN',
       'Davis Cup Finals RR: CRO vs AUS',
       'Davis Cup Finals RR: CRO vs HUN',
       'Davis Cup Finals RR: ITA vs COL',
       'Davis Cup Finals RR: USA vs COL',
       'Davis Cup Finals RR: GER vs AUT',
       'Davis Cup Finals RR: SRB vs AUT',
       'Davis Cup Finals RR: SRB vs GER',
       'Davis Cup Finals SF: CRO vs SRB',
       'Davis Cup Finals QF: ITA vs CRO',
       'Davis Cup Finals F: RTF vs CRO',
       'Davis Cup Finals SF: RTF vs GER',
       'Davis Cup Finals QF: RTF vs SWE',
       'Davis Cup Finals QF: SRB vs KAZ', 'Davis Cup WG1 PO: UKR vs NOR',
       'Davis Cup WG1 R1: ARG vs BLR', 'Davis Cup WG1 R1: BEL vs BOL',
       'Davis Cup WG1 R1: BIH vs PER', 'Davis Cup WG1 R1: BRA vs LBN',
       'Davis Cup WG1 R1: CHI vs SVK', 'Davis Cup WG1 R1: IND vs FIN',
       'Davis Cup WG1 R1: ISR vs UKR', 'Davis Cup WG1 R1: NED vs URU',
       'Davis Cup WG1 R1: POR vs ROU', 'Davis Cup WG1 R1: UZB vs NOR',
       'Davis Cup WG2 PO: TUN vs ZIM', 'Davis Cup WG2 R1: DOM vs TUN',
       'Davis Cup WG2 R1: LTU vs GRE', 'Davis Cup WG2 R1: RSA vs VEN',
       'Davis Cup WG2 R1: SUI vs EST', 'Davis Cup WG2 R1: THA vs DEN',
       'Davis Cup WG2 R1: TUR vs LAT', 'Davis Cup QLS R1: ARG vs CZE',
       'Davis Cup QLS R1: AUS vs HUN', 'Davis Cup QLS R1: BEL vs FIN',
       'Davis Cup QLS R1: CAN vs NED', 'Davis Cup QLS R1: ESP vs ROU',
       'Davis Cup QLS R1: FRA vs ECU', 'Davis Cup QLS R1: GER vs BRA',
       'Davis Cup QLS R1: ITA vs SVK', 'Davis Cup QLS R1: KAZ vs NOR',
       'Davis Cup QLS R1: SWE vs JPN', 'Davis Cup QLS R1: USA vs COL',
       'Davis Cup WG1 PO: CHI vs SLO', 'Davis Cup WG1 PO: IND vs DEN',
       'Davis Cup WG1 PO: UZB vs TUR', 'Davis Cup WG2 PO: EGY vs CYP',
       'Davis Cup WG2 PO: GRE vs JAM', 'United Cup',
       'Davis Cup QLS R1: ARG vs KAZ', 'Davis Cup QLS R1: CAN vs KOR',
       'Davis Cup QLS R1: CHI vs PER', 'Davis Cup QLS R1: CRO vs BEL',
       'Davis Cup QLS R1: CZE vs ISR', 'Davis Cup QLS R1: FIN vs POR',
       'Davis Cup QLS R1: HUN vs GER', 'Davis Cup QLS R1: NED vs SUI',
       'Davis Cup QLS R1: SRB vs SVK', 'Davis Cup QLS R1: SWE vs BRA',
       'Davis Cup QLS R1: TPE vs FRA', 'Davis Cup QLS R1: UKR vs USA',
       'Davis Cup WG1 PO: BUL vs BIH', 'Davis Cup WG1 PO: COL vs LUX',
       'Davis Cup WG1 PO: EGY vs ECU', 'Davis Cup WG1 PO: GRE vs ROU',
       'Davis Cup WG1 PO: IRL vs AUT', 'Davis Cup WG1 PO: LBN vs JPN',
       'Davis Cup WG1 PO: LTU vs GEO', 'Davis Cup WG1 PO: MEX vs DEN',
       'Davis Cup WG1 PO: NOR vs LAT', 'Davis Cup WG1 PO: NZL vs TUR',
       'Davis Cup WG1 PO: UZB vs POL', 'Davis Cup WG2 PO: BOL vs THA',
       'Davis Cup WG2 PO: CHN vs SLO', 'Davis Cup WG2 PO: CYP vs MAR',
       'Davis Cup WG2 PO: HKG vs ZIM', 'Davis Cup WG2 PO: JAM vs BAR',
       'Davis Cup WG2 PO: TOG vs INA', 'Davis Cup WG2 PO: TUN vs CRC',
       'Davis Cup WG2 PO: URU vs MDA', 'Davis Cup WG2 PO: VIE vs RSA'],
      dtype=object)

In [406]:
     # ver como es cada torneo menos la copa davis que va aparte
df_cat[df_cat['tourney_name']=='Tour Finals']['round'].unique()

array(['RR', 4.0, 2.0], dtype=object)

In [407]:
df_cat[df_cat['tourney_name']=='Dusseldorf']['round'].unique()

array(['RR', 2.0, 32.0, 16.0, 8.0, 4.0], dtype=object)

In [408]:
df_cat[df_cat['tourney_name']=='Masters Cup']['round'].unique()

array(['RR', 4.0, 2.0], dtype=object)

In [409]:
    # en Tour Finals y Master Cup RR = 8
indices = []
for i in ['Tour Finals','Masters Cup']:
      indices.append(list(df_cat[(df_cat['tourney_name']==i) & (df_cat['round']=='RR')].index))
RR_indices = list(itertools.chain(*indices))

    #imputacion RR=8
df_cat.loc[RR_indices,'round'] =8

    #comprobación de la imputación
for i in ['Tour Finals','Masters Cup']:
     print(df_cat[df_cat['tourney_name']==i]['round'].unique())

[8 4.0 2.0]
[8 4.0 2.0]

In [410]:
    # imputar RR=64 en 'Dusseldorf'
indices = list(df_cat[(df_cat['tourney_name']=='Dusseldorf') & (df_cat['round']=='RR')].index)

    # imputacion RR=64
df_cat.loc[indices,'round'] = 64

    # comprobacion de la imputacion
df_cat[df_cat['tourney_name']=='Dusseldorf']['round'].value_counts()

round
64      345
2.0      32
32.0     24
16.0     16
8.0       7
4.0       4
Name: count, dtype: int64

In [411]:
df_cat[df_cat['tourney_name']=='United Cup']['round'].unique()

array([2.0, 4.0, 'RR', 8.0], dtype=object)

In [412]:
    # imputacion RR en 'United Cup'
indices = list(df_cat[(df_cat['tourney_name']=='United Cup') & (df_cat['round']=='RR')].index)

    # imputacion RR=16
df_cat.loc[indices,'round'] = 16

    # comprobacion de la imputacion
df_cat[df_cat['tourney_name']=='United Cup']['round'].value_counts()

round
16     53
4.0     6
8.0     4
2.0     2
Name: count, dtype: int64

In [413]:
    # RR que faltan por imputar (copa davis)
df_cat[df_cat['round']=='RR']['tourney_name'].unique()

array(['Davis Cup G1 R1: BAR vs ECU', 'Davis Cup G1 R1: CHI vs DOM',
       'Davis Cup G1 R1: HUN vs ISR', 'Davis Cup G1 R1: NZL vs KOR',
       'Davis Cup G1 R1: PAK vs CHN', 'Davis Cup G1 R1: POR vs AUT',
       'Davis Cup G1 R1: ROU vs SLO', 'Davis Cup G1 R1: RUS vs SWE',
       'Davis Cup G2 R1: BIH vs TUN', 'Davis Cup G2 R1: BUL vs TUR',
       'Davis Cup G2 R1: EGY vs BLR', 'Davis Cup G2 R1: GEO vs DEN',
       'Davis Cup G2 R1: LTU vs NOR', 'Davis Cup G2 R1: MEX vs GUA',
       'Davis Cup G2 R1: MON vs LAT', 'Davis Cup G2 R1: PHI vs KUW',
       'Davis Cup G2 R1: RSA vs LUX', 'Davis Cup G2 R1: SRI vs THA',
       'Davis Cup G2 R1: VIE vs INA', 'Davis Cup G2 R1: ZIM vs FIN',
       'Davis Cup WG R1: ARG vs POL', 'Davis Cup WG R1: CAN vs FRA',
       'Davis Cup WG R1: CRO vs BEL', 'Davis Cup WG R1: GBR vs JPN',
       'Davis Cup WG R1: GER vs CZE', 'Davis Cup WG R1: SRB vs KAZ',
       'Davis Cup WG R1: SUI vs ITA', 'Davis Cup WG R1: USA vs AUS',
       'Davis Cup G1 R2: BRA vs ECU', 'Davis Cup G1 R2: CHI vs COL',
       'Davis Cup G1 R2: CHN vs UZB', 'Davis Cup G1 R2: ESP vs ROU',
       'Davis Cup G1 R2: HUN vs SVK', 'Davis Cup G1 R2: IND vs KOR',
       'Davis Cup G1 R2: RUS vs NED', 'Davis Cup G1 R2: UKR vs AUT',
       'Davis Cup G2 R2: ESA vs VEN', 'Davis Cup G2 R2: FIN vs DEN',
       'Davis Cup G2 R2: LAT vs BLR', 'Davis Cup G2 R2: LTU vs RSA',
       'Davis Cup G2 R2: PER vs MEX', 'Davis Cup G2 R2: TPE vs PHI',
       'Davis Cup G2 R2: TUR vs BIH', 'Davis Cup WG QF: FRA vs CZE',
       'Davis Cup WG QF: GBR vs SRB', 'Davis Cup WG QF: ITA vs ARG',
       'Davis Cup WG QF: USA vs CRO', 'Davis Cup G2 R3: BLR vs DEN',
       'Davis Cup G2 R3: LTU vs BIH', 'Davis Cup G2 R3: PER vs VEN',
       'Davis Cup G2 R3: TPE vs THA', 'Davis Cup WG PO: AUS vs SVK',
       'Davis Cup WG PO: BEL vs BRA', 'Davis Cup WG PO: CAN vs CHI',
       'Davis Cup WG PO: ESP vs IND', 'Davis Cup WG PO: GER vs POL',
       'Davis Cup WG PO: JPN vs UKR', 'Davis Cup WG PO: KAZ vs RUS',
       'Davis Cup WG PO: SUI vs UZB', 'Davis Cup WG SF: FRA vs CRO',
       'Davis Cup WG SF: GBR vs ARG', 'Davis Cup WG F: ARG vs CRO',
       'Davis Cup G1 R1: DOM vs CHI', 'Davis Cup G1 R1: ISR vs POR',
       'Davis Cup G1 R1: NZL vs IND', 'Davis Cup G1 R1: PER vs ECU',
       'Davis Cup G1 R1: POL vs BIH', 'Davis Cup G1 R1: ROU vs BLR',
       'Davis Cup G1 R1: UZB vs KOR', 'Davis Cup G1 R2: SVK vs HUN',
       'Davis Cup G2 R1: BOL vs ESA', 'Davis Cup G2 R1: EST vs RSA',
       'Davis Cup G2 R1: FIN vs GEO', 'Davis Cup G2 R1: INA vs PHI',
       'Davis Cup G2 R1: KUW vs THA', 'Davis Cup G2 R1: MAR vs DEN',
       'Davis Cup G2 R1: MON vs SLO', 'Davis Cup G2 R1: NOR vs LAT',
       'Davis Cup G2 R1: SWE vs TUN', 'Davis Cup G2 R1: TUR vs CYP',
       'Davis Cup G2 R1: VIE vs HKG', 'Davis Cup WG R1: ARG vs ITA',
       'Davis Cup WG R1: BEL vs GER', 'Davis Cup WG R1: CAN vs GBR',
       'Davis Cup WG R1: CZE vs AUS', 'Davis Cup WG R1: ESP vs CRO',
       'Davis Cup WG R1: JPN vs FRA', 'Davis Cup WG R1: RUS vs SRB',
       'Davis Cup WG R1: SUI vs USA', 'Davis Cup G1 R1: TPE vs CHN',
       'Davis Cup G1 R2: BLR vs AUT', 'Davis Cup G1 R2: KAZ vs CHN',
       'Davis Cup G1 R2: NED vs BIH', 'Davis Cup G1 R2: POR vs UKR',
       'Davis Cup G1 R2: UZB vs IND', 'Davis Cup G2 R2: BAR vs GUA',
       'Davis Cup G2 R2: LTU vs GEO', 'Davis Cup G2 R2: NOR vs DEN',
       'Davis Cup G2 R2: RSA vs SLO', 'Davis Cup G2 R2: SWE vs TUR',
       'Davis Cup WG QF: AUS vs USA', 'Davis Cup WG QF: FRA vs GBR',
       'Davis Cup WG QF: ITA vs BEL', 'Davis Cup WG QF: SRB vs ESP',
       'Davis Cup G2 R3: BAR vs VEN', 'Davis Cup G2 R3: DEN vs RSA',
       'Davis Cup G2 R3: SWE vs LTU', 'Davis Cup WG PO: ARG vs KAZ',
       'Davis Cup WG PO: CAN vs IND', 'Davis Cup WG PO: CRO vs COL',
       'Davis Cup WG PO: CZE vs NED', 'Davis Cup WG PO: GER vs POR',
       'Davis Cup WG PO: JPN vs BRA', 'Davis Cup WG PO: RUS vs HUN',
       'Davis Cup WG PO: SUI vs BLR', 'Davis Cup WG SF: BEL vs AUS',
       'Davis Cup WG SF: FRA vs SRB', 'Davis Cup WG F: BEL vs FRA',
       'Davis Cup G1 R1: AUT vs BLR', 'Davis Cup G1 R1: CHI vs ECU',
       'Davis Cup G1 R1: CHN vs NZL', 'Davis Cup G1 R1: COL vs BAR',
       'Davis Cup G1 R1: DOM vs BRA', 'Davis Cup G1 R1: KOR vs PAK',
       'Davis Cup G1 R1: RSA vs ISR', 'Davis Cup G1 R1: UKR vs SWE',
       'Davis Cup WG R1: AUS vs GER', 'Davis Cup WG R1: CAN vs CRO',
       'Davis Cup WG R1: FRA vs NED', 'Davis Cup WG R1: GBR vs ESP',
       'Davis Cup WG R1: HUN vs BEL', 'Davis Cup WG R1: ITA vs JPN',
       'Davis Cup WG R1: KAZ vs SUI', 'Davis Cup WG R1: USA vs SRB',
       'Davis Cup G2 R1: BOL vs PER', 'Davis Cup G2 R1: EGY vs NOR',
       'Davis Cup G2 R1: ESA vs URU', 'Davis Cup G2 R1: EST vs LTU',
       'Davis Cup G2 R1: GEO vs MAR', 'Davis Cup G2 R1: IRI vs HKG',
       'Davis Cup G2 R1: IRL vs DEN', 'Davis Cup G2 R1: LBN vs TPE',
       'Davis Cup G2 R1: PHI vs INA', 'Davis Cup G2 R1: SLO vs POL',
       'Davis Cup G2 R1: THA vs SRI', 'Davis Cup G2 R1: TUN vs FIN',
       'Davis Cup G2 R1: TUR vs ZIM', 'Davis Cup G2 R1: VEN vs GUA',
       'Davis Cup G1 R2: ARG vs CHI', 'Davis Cup G1 R2: AUT vs RUS',
       'Davis Cup G1 R2: BIH vs SVK', 'Davis Cup G1 R2: COL vs BRA',
       'Davis Cup G1 R2: CZE vs ISR', 'Davis Cup G1 R2: IND vs CHN',
       'Davis Cup G1 R2: PAK vs UZB', 'Davis Cup G1 R2: POR vs SWE',
       'Davis Cup WG QF: ESP vs GER', 'Davis Cup WG QF: FRA vs ITA',
       'Davis Cup WG QF: KAZ vs CRO', 'Davis Cup WG QF: USA vs BEL',
       'Davis Cup G2 R2: EGY vs DEN', 'Davis Cup G2 R2: FIN vs LTU',
       'Davis Cup G2 R2: HKG vs LBN', 'Davis Cup G2 R2: MEX vs PER',
       'Davis Cup G2 R2: POL vs ZIM', 'Davis Cup G2 R2: ROU vs MAR',
       'Davis Cup G2 R2: THA vs PHI', 'Davis Cup G2 R2: VEN vs URU',
       'Davis Cup G2 R3: EGY vs FIN', 'Davis Cup WG PO: ARG vs COL',
       'Davis Cup WG PO: AUT vs AUS', 'Davis Cup WG PO: CAN vs NED',
       'Davis Cup WG PO: GBR vs UZB', 'Davis Cup WG PO: HUN vs CZE',
       'Davis Cup WG PO: JPN vs BIH', 'Davis Cup WG PO: SRB vs IND',
       'Davis Cup WG PO: SUI vs SWE', 'Davis Cup WG SF: CRO vs USA',
       'Davis Cup WG SF: FRA vs ESP', 'Davis Cup G2 R3: ROU vs POL',
       'Davis Cup G2 R3: THA vs LBN', 'Davis Cup G2 R3: URU vs MEX',
       'Davis Cup WG F: FRA vs CRO', 'Davis Cup Finals RR: FRA vs JPN',
       'Davis Cup Finals RR: FRA vs SRB',
       'Davis Cup Finals RR: SRB vs JPN',
       'Davis Cup Finals RR: CRO vs ESP',
       'Davis Cup Finals RR: CRO vs RUS',
       'Davis Cup Finals RR: ESP vs RUS',
       'Davis Cup Finals RR: ARG vs CHI',
       'Davis Cup Finals RR: ARG vs GER',
       'Davis Cup Finals RR: GER vs CHI',
       'Davis Cup Finals RR: AUS vs COL',
       'Davis Cup Finals RR: BEL vs AUS',
       'Davis Cup Finals RR: BEL vs COL',
       'Davis Cup Finals RR: GBR vs KAZ',
       'Davis Cup Finals RR: GBR vs NED',
       'Davis Cup Finals RR: KAZ vs NED',
       'Davis Cup Finals RR: ITA vs CAN',
       'Davis Cup Finals RR: USA vs CAN',
       'Davis Cup Finals RR: USA vs ITA',
       'Davis Cup Finals QF: ARG vs ESP',
       'Davis Cup Finals QF: AUS vs CAN',
       'Davis Cup Finals F: CAN vs ESP',
       'Davis Cup Finals SF: GBR vs ESP',
       'Davis Cup Finals QF: GBR vs GER',
       'Davis Cup Finals SF: RUS vs CAN',
       'Davis Cup Finals QF: SRB vs RUS', 'Davis Cup QLS R1: AUS vs BIH',
       'Davis Cup QLS R1: AUT vs CHI', 'Davis Cup QLS R1: BEL vs BRA',
       'Davis Cup QLS R1: CAN vs SVK', 'Davis Cup QLS R1: CZE vs NED',
       'Davis Cup QLS R1: GER vs HUN', 'Davis Cup QLS R1: ITA vs IND',
       'Davis Cup QLS R1: JPN vs CHN', 'Davis Cup QLS R1: KAZ vs POR',
       'Davis Cup QLS R1: SRB vs UZB', 'Davis Cup QLS R1: SUI vs RUS',
       'Davis Cup QLS R1: SWE vs COL', 'Atp Cup',
       'Davis Cup QLS R1: ARG vs COL', 'Davis Cup QLS R1: AUS vs BRA',
       'Davis Cup QLS R1: AUT vs URU', 'Davis Cup QLS R1: BEL vs HUN',
       'Davis Cup QLS R1: CRO vs IND', 'Davis Cup QLS R1: CZE vs SVK',
       'Davis Cup QLS R1: GER vs BLR', 'Davis Cup QLS R1: JPN vs ECU',
       'Davis Cup QLS R1: KAZ vs NED', 'Davis Cup QLS R1: SWE vs CHI',
       'Davis Cup QLS R1: USA vs UZB', 'Davis Cup WG1 PO: BIH vs RSA',
       'Davis Cup WG1 PO: BOL vs DOM', 'Davis Cup WG1 PO: LBN vs THA',
       'Davis Cup WG1 PO: LTU vs POR', 'Davis Cup WG1 PO: MEX vs FIN',
       'Davis Cup WG1 PO: NOR vs BAR', 'Davis Cup WG1 PO: PER vs SUI',
       'Davis Cup WG1 PO: TUR vs ISR', 'Davis Cup WG1 PO: UKR vs TPE',
       'Davis Cup WG1 PO: VEN vs NZL', 'Davis Cup Finals RR: ESP vs ECU',
       'Davis Cup Finals RR: ESP vs RTF',
       'Davis Cup Finals RR: RTF vs ECU',
       'Davis Cup Finals RR: CAN vs KAZ',
       'Davis Cup Finals RR: CAN vs SWE',
       'Davis Cup Finals RR: KAZ vs SWE',
       'Davis Cup Finals RR: FRA vs CZE',
       'Davis Cup Finals RR: FRA vs GBR',
       'Davis Cup Finals RR: GBR vs CZE',
       'Davis Cup Finals RR: AUS vs HUN',
       'Davis Cup Finals RR: CRO vs AUS',
       'Davis Cup Finals RR: CRO vs HUN',
       'Davis Cup Finals RR: ITA vs COL',
       'Davis Cup Finals RR: USA vs COL',
       'Davis Cup Finals RR: GER vs AUT',
       'Davis Cup Finals RR: SRB vs AUT',
       'Davis Cup Finals RR: SRB vs GER',
       'Davis Cup Finals SF: CRO vs SRB',
       'Davis Cup Finals QF: ITA vs CRO',
       'Davis Cup Finals F: RTF vs CRO',
       'Davis Cup Finals SF: RTF vs GER',
       'Davis Cup Finals QF: RTF vs SWE',
       'Davis Cup Finals QF: SRB vs KAZ', 'Davis Cup WG1 PO: UKR vs NOR',
       'Davis Cup WG1 R1: ARG vs BLR', 'Davis Cup WG1 R1: BEL vs BOL',
       'Davis Cup WG1 R1: BIH vs PER', 'Davis Cup WG1 R1: BRA vs LBN',
       'Davis Cup WG1 R1: CHI vs SVK', 'Davis Cup WG1 R1: IND vs FIN',
       'Davis Cup WG1 R1: ISR vs UKR', 'Davis Cup WG1 R1: NED vs URU',
       'Davis Cup WG1 R1: POR vs ROU', 'Davis Cup WG1 R1: UZB vs NOR',
       'Davis Cup WG2 PO: TUN vs ZIM', 'Davis Cup WG2 R1: DOM vs TUN',
       'Davis Cup WG2 R1: LTU vs GRE', 'Davis Cup WG2 R1: RSA vs VEN',
       'Davis Cup WG2 R1: SUI vs EST', 'Davis Cup WG2 R1: THA vs DEN',
       'Davis Cup WG2 R1: TUR vs LAT', 'Davis Cup QLS R1: ARG vs CZE',
       'Davis Cup QLS R1: AUS vs HUN', 'Davis Cup QLS R1: BEL vs FIN',
       'Davis Cup QLS R1: CAN vs NED', 'Davis Cup QLS R1: ESP vs ROU',
       'Davis Cup QLS R1: FRA vs ECU', 'Davis Cup QLS R1: GER vs BRA',
       'Davis Cup QLS R1: ITA vs SVK', 'Davis Cup QLS R1: KAZ vs NOR',
       'Davis Cup QLS R1: SWE vs JPN', 'Davis Cup QLS R1: USA vs COL',
       'Davis Cup WG1 PO: CHI vs SLO', 'Davis Cup WG1 PO: IND vs DEN',
       'Davis Cup WG1 PO: UZB vs TUR', 'Davis Cup WG2 PO: EGY vs CYP',
       'Davis Cup WG2 PO: GRE vs JAM', 'Davis Cup QLS R1: ARG vs KAZ',
       'Davis Cup QLS R1: CAN vs KOR', 'Davis Cup QLS R1: CHI vs PER',
       'Davis Cup QLS R1: CRO vs BEL', 'Davis Cup QLS R1: CZE vs ISR',
       'Davis Cup QLS R1: FIN vs POR', 'Davis Cup QLS R1: HUN vs GER',
       'Davis Cup QLS R1: NED vs SUI', 'Davis Cup QLS R1: SRB vs SVK',
       'Davis Cup QLS R1: SWE vs BRA', 'Davis Cup QLS R1: TPE vs FRA',
       'Davis Cup QLS R1: UKR vs USA', 'Davis Cup WG1 PO: BUL vs BIH',
       'Davis Cup WG1 PO: COL vs LUX', 'Davis Cup WG1 PO: EGY vs ECU',
       'Davis Cup WG1 PO: GRE vs ROU', 'Davis Cup WG1 PO: IRL vs AUT',
       'Davis Cup WG1 PO: LBN vs JPN', 'Davis Cup WG1 PO: LTU vs GEO',
       'Davis Cup WG1 PO: MEX vs DEN', 'Davis Cup WG1 PO: NOR vs LAT',
       'Davis Cup WG1 PO: NZL vs TUR', 'Davis Cup WG1 PO: UZB vs POL',
       'Davis Cup WG2 PO: BOL vs THA', 'Davis Cup WG2 PO: CHN vs SLO',
       'Davis Cup WG2 PO: CYP vs MAR', 'Davis Cup WG2 PO: HKG vs ZIM',
       'Davis Cup WG2 PO: JAM vs BAR', 'Davis Cup WG2 PO: TOG vs INA',
       'Davis Cup WG2 PO: TUN vs CRC', 'Davis Cup WG2 PO: URU vs MDA',
       'Davis Cup WG2 PO: VIE vs RSA'], dtype=object)

In [414]:
    # comprobacion si ronda en el nombre == round (#no son iguales)
df_cat[df_cat['tourney_name']=='Davis Cup G1 R1: BAR vs ECU']

,tourney_name,surface,tourney_level,winner_name,winner_hand,winner_ioc,loser_name,loser_hand,loser_ioc,score,round
68594,Davis Cup G1 R1: BAR vs ECU,Clay,D,Ivan Endara,R,ECU,Darian King,R,BAR,6-1 6-2 6-4,RR

In [415]:
df[df['tourney_name'].str.startswith('Davis')]

,tourney_name,surface,draw_size,tourney_level,tourney_date,winner_id,winner_name,winner_hand,winner_ht,winner_ioc,...,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,sets
68594,Davis Cup G1 R1: BAR vs ECU,Clay,4.0,D,20160304,105111,Ivan Endara,R,NaN,ECU,...,29.0,11.0,12.0,6.0,13.0,395.0,108.0,243.0,217.0,3
68595,Davis Cup G1 R1: CHI vs DOM,Clay,4.0,D,20160304,105070,Hans Podlipnik Castillo,R,183.0,CHI,...,37.0,14.0,13.0,10.0,16.0,198.0,267.0,1250.0,6.0,3
68596,Davis Cup G1 R1: CHI vs DOM,Clay,4.0,D,20160304,106174,Gonzalo Lama,R,180.0,CHI,...,55.0,10.0,16.0,5.0,8.0,263.0,199.0,222.0,234.0,3
68597,Davis Cup G1 R1: CHI vs DOM,Clay,4.0,D,20160304,106174,Gonzalo Lama,R,180.0,CHI,...,17.0,9.0,8.0,2.0,6.0,263.0,199.0,1250.0,6.0,2
68598,Davis Cup G1 R1: HUN vs ISR,Clay,4.0,D,20160304,105954,Peter Nagy,R,180.0,HUN,...,41.0,23.0,22.0,8.0,19.0,612.0,50.0,89.0,613.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89201,Davis Cup WG2 PO: URU vs MDA,Clay,4.0,D,20240203,105430,Radu Albot,R,175.0,MDA,...,13.0,6.0,8.0,0.0,6.0,136.0,489.0,1109.0,8.0,2
89202,Davis Cup WG2 PO: URU vs MDA,Clay,4.0,D,20240203,105430,Radu Albot,R,175.0,MDA,...,33.0,6.0,8.0,6.0,11.0,136.0,489.0,616.0,55.0,2
89203,Davis Cup WG2 PO: URU vs MDA,Clay,4.0,D,20240203,212051,Joaquin Aguilar Cardozo,U,NaN,URU,...,17.0,7.0,6.0,8.0,14.0,1109.0,8.0,740.0,34.0,2
89204,Davis Cup WG2 PO: VIE vs RSA,Hard,4.0,D,20240202,122533,Nam Hoang Ly,R,NaN,VIE,...,25.0,6.0,9.0,1.0,4.0,554.0,67.0,748.0,32.0,2
89205,Davis Cup WG2 PO: VIE vs RSA,Hard,4.0,D,20240202,122533,Nam Hoang Ly,R,NaN,VIE,...,32.0,17.0,14.0,5.0,9.0,554.0,67.0,416.0,109.0,3

In [416]:
lista=[]
for i in df_cat[df_cat['tourney_name'].str.startswith('Davis')]['tourney_name']:
    c = re.findall(r'(\w{1,2}):', i)
    lista.append(c)
lista

[['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['R3'],
 ['R3'],
 ['R3'],
 ['R3'],
 ['R3'],
 ['R3'],
 ['R3'],
 ['R3'],
 ['R3'],
 ['R3'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['SF'],
 ['SF'],
 ['SF'],
 ['SF'],
 ['SF'],
 ['SF'],
 ['SF'],
 ['F'],
 ['F'],
 ['F'],
 ['F'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['R3'],
 ['R3'],
 ['R3'],
 ['R3'],
 ['R3'],
 ['R3'],
 ['R3'],
 ['R3'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['SF'],
 ['SF'],
 ['SF'],
 ['SF'],
 ['SF'],
 ['SF'],
 ['SF'],
 ['F'],
 ['F'],
 ['F'],
 ['F'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R3'],
 ['R3'],
 ['R3'],
 ['R3'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['SF'],
 ['SF'],
 ['SF'],
 ['SF'],
 ['SF'],
 ['SF'],
 ['SF'],
 ['SF'],
 ['R3'],
 ['R3'],
 ['R3'],
 ['R3'],
 ['R3'],
 ['R3'],
 ['R3'],
 ['R3'],
 ['R3'],
 ['R3'],
 ['F'],
 ['F'],
 ['F'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['F'],
 ['F'],
 ['SF'],
 ['SF'],
 ['QF'],
 ['QF'],
 ['SF'],
 ['SF'],
 ['QF'],
 ['QF'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['RR'],
 ['SF'],
 ['SF'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['F'],
 ['F'],
 ['SF'],
 ['SF'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['QF'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['PO'],
 ['PO'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO'],
 ['PO']]

In [417]:
    # lista con los indices de las filas a cambiar round por ronda en el nombre 
filtro = list(df_cat[df_cat['tourney_name'].str.startswith('Davis')].index)

    # imputacion de las rondas en los nombres a los valores de 'round'
df_cat.loc[filtro, 'round'] = lista

In [418]:
    # valores unicos de las variables (round ahora con nuevos alfanumericos por la copa davis)
for i in ['surface', 'tourney_level','winner_hand','loser_hand','round']:
     print(df_cat[i].unique())

['Hard' 'Carpet' 'Clay' 'Grass']
['A' 'G' 'M' 'F' 'D']
['R' 'L' 'A' 'U']
['R' 'L' 'U' 'A']
[32.0 16.0 8.0 4.0 2.0 128.0 64.0 'R1' 'R2' 'QF' 'R3' 'PO' 'SF' 'F' 'RR']

In [419]:
    # nuevo diccionario para imputar valores con alfanumericos en round del torneo Copa Davis
{'F':2,'SF':4,'QF':8,'R3':16,'R2':32,'R1':64,'PO':128,'RR':256}

{'F': 2, 'SF': 4, 'QF': 8, 'R3': 16, 'R2': 32, 'R1': 64, 'PO': 128, 'RR': 256}

In [420]:
# rondas quitar la R a las que tienen numero 
rondas = {'F':2,'SF':4,'QF':8,'R3':16,'R2':32,'R1':64,'PO':128,'RR':256}
df_cat['round'] = df_cat['round'].map(rondas).fillna(df_cat['round'])

In [421]:
for i in ['surface', 'tourney_level','winner_hand','loser_hand','round']:
    print(df_cat[i].unique())

['Hard' 'Carpet' 'Clay' 'Grass']
['A' 'G' 'M' 'F' 'D']
['R' 'L' 'A' 'U']
['R' 'L' 'U' 'A']
[ 32.  16.   8.   4.   2. 128.  64. 256.]

In [422]:
df_cat

,tourney_name,surface,tourney_level,winner_name,winner_hand,winner_ioc,loser_name,loser_hand,loser_ioc,score,round
0,Auckland,Hard,A,Emilio Sanchez,R,ESP,Renzo Furlan,R,ITA,6-4 6-1,32.0
1,Auckland,Hard,A,Malivai Washington,R,USA,Steve Guy,R,NZL,6-3 6-2,32.0
2,Auckland,Hard,A,Jean Philippe Fleurian,R,FRA,Brett Steven,R,NZL,2-6 6-1 6-2,32.0
3,Auckland,Hard,A,Eric Jelen,R,GER,Gilad Bloom,L,ISR,6-3 1-6 6-4,32.0
4,Auckland,Hard,A,Chuck Adams,R,USA,Richard Fromberg,R,AUS,6-3 6-4,32.0
...,...,...,...,...,...,...,...,...,...,...,...
89201,Davis Cup WG2 PO: URU vs MDA,Clay,D,Radu Albot,R,MDA,Joaquin Aguilar Cardozo,U,URU,6-2 6-3,128.0
89202,Davis Cup WG2 PO: URU vs MDA,Clay,D,Radu Albot,R,MDA,Franco Roncadelli,L,URU,6-3 6-1,128.0
89203,Davis Cup WG2 PO: URU vs MDA,Clay,D,Joaquin Aguilar Cardozo,U,URU,Ilya Snitari,U,MDA,6-1 6-0,128.0
89204,Davis Cup WG2 PO: VIE vs RSA,Hard,D,Nam Hoang Ly,R,VIE,Philip Henning,R,RSA,6-3 6-4,128.0
89205,Davis Cup WG2 PO: VIE vs RSA,Hard,D,Nam Hoang Ly,R,VIE,Kris Van Wyk,U,RSA,6-4 3-6 6-3,128.0

In [423]:
df_cat.isnull().sum()

tourney_name     0
surface          0
tourney_level    0
winner_name      0
winner_hand      0
winner_ioc       0
loser_name       0
loser_hand       0
loser_ioc        0
score            0
round            0
dtype: int64

# LIMPIO_FINAL

In [424]:
df2 = pd.concat([df_num, df_cat], axis=1)
df2

,draw_size,tourney_date,winner_id,winner_ht,winner_age,loser_id,loser_ht,loser_age,best_of,minutes,...,surface,tourney_level,winner_name,winner_hand,winner_ioc,loser_name,loser_hand,loser_ioc,score,round
0,32.0,19910107,101142,180.000000,25.6,101746,175.000000,20.6,3,63.0,...,Hard,A,Emilio Sanchez,R,ESP,Renzo Furlan,R,ITA,6-4 6-1,32.0
1,32.0,19910107,101613,180.000000,21.5,100587,188.000000,31.8,3,72.0,...,Hard,A,Malivai Washington,R,USA,Steve Guy,R,NZL,6-3 6-2,32.0
2,32.0,19910107,101179,185.000000,25.3,101601,185.000000,21.6,3,101.0,...,Hard,A,Jean Philippe Fleurian,R,FRA,Brett Steven,R,NZL,2-6 6-1 6-2,32.0
3,32.0,19910107,101117,180.000000,25.8,101332,173.000000,23.8,3,108.0,...,Hard,A,Eric Jelen,R,GER,Gilad Bloom,L,ISR,6-3 1-6 6-4,32.0
4,32.0,19910107,101901,185.000000,19.7,101735,196.000000,20.6,3,65.0,...,Hard,A,Chuck Adams,R,USA,Richard Fromberg,R,AUS,6-3 6-4,32.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89201,4.0,20240203,105430,175.000000,34.2,212051,185.267928,18.8,3,81.0,...,Clay,D,Radu Albot,R,MDA,Joaquin Aguilar Cardozo,U,URU,6-2 6-3,128.0
89202,4.0,20240203,105430,175.000000,34.2,208364,185.000000,23.9,3,95.0,...,Clay,D,Radu Albot,R,MDA,Franco Roncadelli,L,URU,6-3 6-1,128.0
89203,4.0,20240203,212051,185.832809,18.8,209943,185.267928,21.8,3,77.0,...,Clay,D,Joaquin Aguilar Cardozo,U,URU,Ilya Snitari,U,MDA,6-1 6-0,128.0
89204,4.0,20240202,122533,185.832809,26.9,202475,185.267928,23.2,3,131.0,...,Hard,D,Nam Hoang Ly,R,VIE,Philip Henning,R,RSA,6-3 6-4,128.0
89205,4.0,20240202,122533,185.832809,26.9,144748,185.267928,27.3,3,159.0,...,Hard,D,Nam Hoang Ly,R,VIE,Kris Van Wyk,U,RSA,6-4 3-6 6-3,128.0

In [425]:
df2.isnull().sum()

draw_size             0
tourney_date          0
winner_id             0
winner_ht             0
winner_age            0
loser_id              0
loser_ht              0
loser_age             0
best_of               0
minutes               0
w_ace                 0
w_df                  0
w_svpt                0
w_1stIn               0
w_1stWon              0
w_2ndWon              0
w_SvGms               0
w_bpSaved             0
w_bpFaced             0
l_ace                 0
l_df                  0
l_svpt                0
l_1stIn               0
l_1stWon              0
l_2ndWon              0
l_SvGms               0
l_bpSaved             0
l_bpFaced             0
winner_rank           0
winner_rank_points    0
loser_rank            0
loser_rank_points     0
sets                  0
tourney_name          0
surface               0
tourney_level         0
winner_name           0
winner_hand           0
winner_ioc            0
loser_name            0
loser_hand            0
loser_ioc             0
score                 0
round                 0
dtype: int64

In [428]:
df2.to_csv('limpio_final.csv',index=False)